version: '3'

services:
  coursework:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: coursework
    depends_on:
      - courseworkdb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://courseworkdb:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"


  courseworkdb:
    image: 'postgres:13.1-alpine'
    container_name: courseworkdb
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"